Document: zenpower-dkms
Title: Debian zenpower-dkms Manual
Author: <insert document author here>
Abstract: This manual describes what zenpower-dkms is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/zenpower-dkms/zenpower-dkms.sgml.gz

Format: postscript
Files: /usr/share/doc/zenpower-dkms/zenpower-dkms.ps.gz

Format: text
Files: /usr/share/doc/zenpower-dkms/zenpower-dkms.text.gz

Format: HTML
Index: /usr/share/doc/zenpower-dkms/html/index.html
Files: /usr/share/doc/zenpower-dkms/html/*.html
